# Docker compose file for joomla and mysql application
services:
  joomla_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
    volumes:
      - joomla_mysql_data:/var/lib/mysql

  joomla_files:
    image: joomla
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomla_mysql
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla
    volumes:
      - joomla_files_data:/var/www/html
    depends_on:
      - joomla_mysql

volumes:
  joomla_mysql_data:
  joomla_files_data: