# Docker compose file for wordpress and mysql application
services:
  wp_mysql:
    image: mysql
    restart: always
    ports:
      - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - wp_mysql_data:/var/lib/mysql
    networks:
      - wp_network

  wp_files:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wp_mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_files_data:/var/www/html
    depends_on:
      - wp_mysql
    networks:
      - wp_network

volumes:
  wp_mysql_data:
  wp_files_data:

networks:
  default:
      name: wp_network
  wp_network:
      driver: bridge